### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by emiliopedrollo** [antonioribeiro/version#19]
When I try to install using composer this is what i get:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/routing v3.4.0
    - Conclusion: don't install symfony/routing v3.4.0
    - Installation request for pragmarx/version ^0.2.1 -> satisfiable by pragmarx/version[v0.2.1].
    - symfony/yaml v3.3.0 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.1 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.10 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.11 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.12 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.13 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.2 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.3 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.4 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.5 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.6 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.7 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.8 conflicts with symfony/routing[v3.4.0].
    - symfony/yaml v3.3.9 conflicts with symfony/routing[v3.4.0].
    - Installation request for symfony/routing (locked at v3.4.0) -> satisfiable by symfony/routing[v3.4.0].
    - pragmarx/version v0.2.1 requires pragmarx/yaml ^0.1 -> satisfiable by pragmarx/yaml[v0.1.0, v0.1.1, v0.1.2, v0.1.3].
    - pragmarx/yaml v0.1.3 requires symfony/yaml ^3.3 -> satisfiable by symfony/yaml[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
    - pragmarx/yaml v0.1.2 requires symfony/yaml ^3.3 -> satisfiable by symfony/yaml[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
    - pragmarx/yaml v0.1.1 requires symfony/yaml ~3.3 -> satisfiable by symfony/yaml[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
    - pragmarx/yaml v0.1.0 requires symfony/yaml ~3.3 -> satisfiable by symfony/yaml[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
    - Conclusion: don't install symfony/yaml v3.4.0|install symfony/yaml v3.3.0|install symfony/yaml v3.3.1|install symfony/yaml v3.3.10|install symfony/yaml v3.3.11|install symfony/yaml v3.3.12|install symfony/yaml v3.3.13|install symfony/yaml v3.3.2|install symfony/yaml v3.3.3|install symfony/yaml v3.3.4|install symfony/yaml v3.3.5|install symfony/yaml v3.3.6|install symfony/yaml v3.3.7|install symfony/yaml v3.3.8|install symfony/yaml v3.3.9


Installation failed, reverting ./composer.json to its original content.
```

**Comment by antonioribeiro** [comment]
Not sure why you are getting this, by the constraints you should be able to use Symfony 3.3 and 3.4:

![image](https://user-images.githubusercontent.com/3182864/33550971-f87d35c0-d8d6-11e7-8f59-bdb62c4875e8.png)

**Comment by antonioribeiro** [comment]
Are you able to share your app's composer.json?

**Comment by antonioribeiro** [comment]
This message may also help you

![image](https://user-images.githubusercontent.com/3182864/33551128-83dc6532-d8d7-11e7-9a56-8a810f651f4e.png)

**Comment by emiliopedrollo** [comment]
Running `composer update` didn't help. Here's the contents of my `composer.json` file:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "repositories":[
        {
            "type":"vcs",
            "url":"https://github.com/emiliopedrollo/passport"
        },
        {
            "type":"vcs",
            "url":"https://github.com/gilesrussi/laravel-apidoc-generator"
        },
        {
            "type":"vcs",
            "url":"https://github.com/gilesrussi/laravel-log-viewer"
        }
    ],
    "extra":{
        "laravel":{
            "dont-discover":[
                "laravel/passport"
            ]
        }
    },
    "require": {
        "php": ">=7.1.4",
        "barryvdh/laravel-cors": "^0.9.2",
        "barryvdh/laravel-debugbar": "^3.0@dev",
        "cviebrock/eloquent-sluggable": "^4.2",
        "emiliopedrollo/laravel-postgres-extended-schema": "dev-master",
        "firebase/php-jwt": "^5.0",
        "hedronium/spaceless-blade": "^2.0",
        "huang-yi/laravel-swoole-http": "^2.0",
        "jailtonsc/laravel-response-xml": "^2.0",
        "jenssegers/agent": "^2.5",
        "laravel/framework": "5.5.*",
        "laravel/passport": "dev-uuid",
        "laravel/tinker": "~1.0",
        "mpociot/laravel-apidoc-generator": "dev-dev-sf",
        "n7olkachev/laravel-computed-properties": "^1.1",
        "plank/laravel-metable": "^1.0",
        "rap2hpoutre/laravel-log-viewer": "dev-dev",
        "yajra/laravel-datatables-oracle": "8.*"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.4",
        "doctrine/dbal": "^2.5",
        "eaglewu/swoole-ide-helper": "dev-master",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/Support/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan ide-helper:models -W"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
```

**Comment by emiliopedrollo** [comment]
Maybe you will have to remove the line `"emiliopedrollo/laravel-postgres-extended-schema": "dev-master",` as it requires a token to install.

**Comment by antonioribeiro** [comment]
Just intalled it here, using your composer.json untouched. Remove your composer.lock and vendor folder and do a `composer install`:

````
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 116 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.5.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing doctrine/dbal (v2.6.3): Loading from cache
  - Installing paragonie/random_compat (v2.0.11): Loading from cache
  - Installing ramsey/uuid (3.7.1): Loading from cache
  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache
  - Installing symfony/css-selector (v3.4.0): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/var-dumper (v3.4.0): Loading from cache
  - Installing symfony/routing (v3.3.13): Loading from cache
  - Installing symfony/process (v3.4.0): Loading from cache
  - Installing symfony/polyfill-php70 (v1.6.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.0): Loading from cache
  - Installing symfony/event-dispatcher (v4.0.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.0): Loading from cache
  - Installing symfony/http-kernel (v3.4.0): Loading from cache
  - Installing symfony/finder (v3.4.0): Loading from cache
  - Installing symfony/console (v3.4.0): Loading from cache
  - Installing egulias/email-validator (2.1.3): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.0.2): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/translation (v3.3.13): Loading from cache
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.1): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing league/flysystem (1.0.41): Loading from cache
  - Installing erusev/parsedown (1.6.4): Loading from cache
  - Installing laravel/framework (v5.5.22): Loading from cache
  - Installing emiliopedrollo/laravel-postgres-extended-schema (dev-master 16c8534): Loading from cache
  - Installing hedronium/spaceless-blade (v2.0.0): Loading from cache
  - Installing jailtonsc/laravel-response-xml (v2): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing zendframework/zend-diactoros (1.6.1): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.0.0): Loading from cache
  - Installing phpseclib/phpseclib (2.0.9): Loading from cache
  - Installing defuse/php-encryption (v2.1.0): Loading from cache
  - Installing lcobucci/jwt (3.2.2): Loading from cache
  - Installing league/event (2.1.2): Loading from cache
  - Installing league/oauth2-server (6.0.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing firebase/php-jwt (v5.0.0): Loading from cache
  - Installing laravel/passport (dev-uuid bbd9855): Loading from cache
  - Installing mpociot/reflection-docblock (1.0.1): Loading from cache
  - Installing windwalker/structure (3.2.8): Loading from cache
  - Installing windwalker/renderer (3.2.8): Loading from cache
  - Installing symfony/yaml (v3.3.13): Loading from cache
  - Installing mnapoli/front-yaml (1.6.0): Loading from cache
  - Installing php-di/invoker (2.0.0): Loading from cache
  - Installing mnapoli/silly (1.7.0): Loading from cache
  - Installing mpociot/documentarian (0.2.1): Loading from cache
  - Installing fzaninotto/faker (v1.7.1): Loading from cache
  - Installing mpociot/laravel-apidoc-generator (dev-dev-sf 03dcb88): Loading from cache
  - Installing rap2hpoutre/laravel-log-viewer (dev-dev 1c68c24): Loading from cache
  - Installing pragmarx/yaml (v0.1.3): Loading from cache
  - Installing pragmarx/version (v0.2.1): Loading from cache
  - Installing eaglewu/swoole-ide-helper (dev-master a30eba7): Loading from cache
  - Installing huang-yi/laravel-swoole-http (2.0.2): Loading from cache
  - Installing mobiledetect/mobiledetectlib (2.8.27): Loading from cache
  - Installing jaybizzle/crawler-detect (v1.2.54): Loading from cache
  - Installing jenssegers/agent (v2.6.0): Loading from cache
  - Installing n7olkachev/laravel-computed-properties (v1.1.1): Loading from cache
  - Installing barryvdh/laravel-cors (v0.9.3): Loading from cache
  - Installing plank/laravel-metable (1.0.4): Loading from cache
  - Installing yajra/laravel-datatables-oracle (v8.3.2): Loading from cache
  - Installing symfony/class-loader (v3.4.0): Loading from cache
  - Installing barryvdh/reflection-docblock (v2.0.4): Loading from cache
  - Installing barryvdh/laravel-ide-helper (v2.4.1): Loading from cache
  - Installing hamcrest/hamcrest-php (v1.2.2): Loading from cache
  - Installing mockery/mockery (0.9.9): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.4): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.4): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.2.0): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.2): Loading from cache
  - Installing maximebf/debugbar (v1.14.1): Loading from cache
  - Installing barryvdh/laravel-debugbar (v3.1.0): Loading from cache
  - Installing cocur/slugify (v3.0.1): Loading from cache
  - Installing cviebrock/eloquent-sluggable (4.3.0): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v3.1.2): Loading from cache
  - Installing psy/psysh (v0.8.15): Loading from cache
  - Installing laravel/tinker (v1.0.2): Loading from cache
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
symfony/console suggests installing symfony/lock ()
egulias/email-validator suggests installing ext-intl (PHP Internationalization Libraries are required to use the SpoofChecking validation)
symfony/translation suggests installing symfony/config ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~3.3).)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
lcobucci/jwt suggests installing mdanter/ecc (Required to use Elliptic Curves based algorithms.)
mpociot/reflection-docblock suggests installing dflydev/markdown (~1.0)
windwalker/renderer suggests installing league/plates (Install 3.* if you require Plates template engine.)
windwalker/renderer suggests installing twig/twig (Install 1.* if you require Twig engine.)
windwalker/renderer suggests installing mustache/mustache (Install 2.* if you require Mustache engine.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-buttons (Plugin for server-side exporting of dataTable.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-html (Plugin for server-side HTML builder of dataTable.)
yajra/laravel-datatables-oracle suggests installing yajra/laravel-datatables-fractal (Plugin for server-side response using Fractal.)
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing predis/predis (Redis storage)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
PHP Warning:  Uncaught ErrorException: require(/Users/antoniocarlos/code/pragmarx/version/vendor/composer/../../app/Support/helpers.php): failed to open stream: No such file or directory in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php:66
Stack trace:
#0 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/Users/...', '/Users/antonioc...', 66, Array)
#1 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(66): require()
#2 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(56): composerRequire82b4fa14f44cca15f402ac794ad8880d('6f63623309b4173...', '/Users/antonioc...')
#3 /Users/antoniocarlos/code/pragmarx/version/vendor/autoload.php(7): ComposerAutoloaderInit82b4fa14f44cca15f402ac794ad8880d::getLoader()
#4 /Users/antoniocarlos/code/pragmarx/version/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/Users/antonioc...')
#5 phar:// in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/Users/antoniocarlos/code/pragmarx/version/vendor/composer/../../app/Support/helpers.php): failed to open stream: No such file or directory in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php:66
Stack trace:
#0 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/Users/...', '/Users/antonioc...', 66, Array)
#1 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(66): require()
#2 /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php(56): composerRequire82b4fa14f44cca15f402ac794ad8880d('6f63623309b4173...', '/Users/antonioc...')
#3 /Users/antoniocarlos/code/pragmarx/version/vendor/autoload.php(7): ComposerAutoloaderInit82b4fa14f44cca15f402ac794ad8880d::getLoader()
#4 /Users/antoniocarlos/code/pragmarx/version/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/Users/antonioc...')
#5 phar:// in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequire82b4fa14f44cca15f402ac794ad8880d(): Failed opening required '/Users/antoniocarlos/code/pragmarx/version/vendor/composer/../../app/Support/helpers.php' (include_path='.:') in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequire82b4fa14f44cca15f402ac794ad8880d(): Failed opening required '/Users/antoniocarlos/code/pragmarx/version/vendor/composer/../../app/Support/helpers.php' (include_path='.:') in /Users/antoniocarlos/code/pragmarx/version/vendor/composer/autoload_real.php on line 66
```

**Comment by antonioribeiro** [comment]
Sorry, I just touched it to add Version:

![image](https://user-images.githubusercontent.com/3182864/33554420-c80f71a2-d8e3-11e7-902f-dd9123ecc11f.png)

**Comment by emiliopedrollo** [comment]
Removing `composer.lock` , edditing the package in `composer.json` and excuting `composer install` seems to be able to install it. Thank you.
